# 默认端口号是 8080 我们可以把它改成 9090
server:
  port: 8080
# 配置spring
spring:
  resources:
    static-locations: classpath:/static/
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  #thymelea模板配置
  thymeleaf:
    #thymeleaf 所在路径
    prefix: classpath:/templates/
    #thymeleaf 后缀
    suffix: .html
    #thymeleaf 采用的标准
    mode: LEGACYHTML5 #HTML5
    #thymeleaf 编码格式
    encoding: UTF-8
    #缓存
    cache: false
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: shop
    password: shop
    #driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
  session:
    #超时一定要大于0
    timeout: 3s
    store-type: redis
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: shop
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #连接池最大连空闲接数
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    #超时
    timeout: 5s
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: /templates/
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
###########spring end
#  jpa:
#    #是否打印sql语句
#    show-sql: true
#
mybatis:
  #  #指定 mybatis 配置文件路径
  #  config-location: classpath:mybatis-config.xml
  #  #指定 mybatis 文件路径
  type-aliases-package: com.example.shop.entity
  mapper-locations: classpath:mapper/*.xml

#showSql

logging:
  pattern:
    #格式化，只能输出日期和内容
    console: "%d - %msg%n"
  level:
    #打印级别
    com.example.shop.ShopApplication: debug
    com.example.shop.dao: debug


